// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tempo.Api.Data;

#nullable disable

namespace Tempo.Api.Migrations
{
    [DbContext(typeof(TempoDbContext))]
    [Migration("20251111023205_AddWorkoutMedia")]
    partial class AddWorkoutMedia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tempo.Api.Models.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AvgPaceS")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DistanceM")
                        .HasColumnType("double precision");

                    b.Property<int>("DurationS")
                        .HasColumnType("integer");

                    b.Property<double?>("ElevGainM")
                        .HasColumnType("double precision");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("RunType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Weather")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("StartedAt", "DistanceM", "DurationS");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("Tempo.Api.Models.WorkoutMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutMedia");
                });

            modelBuilder.Entity("Tempo.Api.Models.WorkoutRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RouteGeoJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId")
                        .IsUnique();

                    b.ToTable("WorkoutRoutes");
                });

            modelBuilder.Entity("Tempo.Api.Models.WorkoutSplit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("DistanceM")
                        .HasColumnType("double precision");

                    b.Property<int>("DurationS")
                        .HasColumnType("integer");

                    b.Property<int>("Idx")
                        .HasColumnType("integer");

                    b.Property<int>("PaceS")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId", "Idx");

                    b.ToTable("WorkoutSplits");
                });

            modelBuilder.Entity("Tempo.Api.Models.WorkoutMedia", b =>
                {
                    b.HasOne("Tempo.Api.Models.Workout", "Workout")
                        .WithMany("Media")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Tempo.Api.Models.WorkoutRoute", b =>
                {
                    b.HasOne("Tempo.Api.Models.Workout", "Workout")
                        .WithOne("Route")
                        .HasForeignKey("Tempo.Api.Models.WorkoutRoute", "WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Tempo.Api.Models.WorkoutSplit", b =>
                {
                    b.HasOne("Tempo.Api.Models.Workout", "Workout")
                        .WithMany("Splits")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Tempo.Api.Models.Workout", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("Route");

                    b.Navigation("Splits");
                });
#pragma warning restore 612, 618
        }
    }
}
