/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

public enum CameraEventType: UInt8, CaseIterable {
    case videoStart = 0
    case videoSplit = 1
    case videoEnd = 2
    case photoTaken = 3
    case videoSecondStreamStart = 4
    case videoSecondStreamSplit = 5
    case videoSecondStreamEnd = 6
    case videoSplitStart = 7
    case videoSecondStreamSplitStart = 8
    case videoPause = 11
    case videoSecondStreamPause = 12
    case videoResume = 13
    case videoSecondStreamResume = 14
    case invalid = 0xFF
}
