/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

public enum CardioExerciseName: UInt16, CaseIterable {
    case bobAndWeaveCircle = 0
    case weightedBobAndWeaveCircle = 1
    case cardioCoreCrawl = 2
    case weightedCardioCoreCrawl = 3
    case doubleUnder = 4
    case weightedDoubleUnder = 5
    case jumpRope = 6
    case weightedJumpRope = 7
    case jumpRopeCrossover = 8
    case weightedJumpRopeCrossover = 9
    case jumpRopeJog = 10
    case weightedJumpRopeJog = 11
    case jumpingJacks = 12
    case weightedJumpingJacks = 13
    case skiMoguls = 14
    case weightedSkiMoguls = 15
    case splitJacks = 16
    case weightedSplitJacks = 17
    case squatJacks = 18
    case weightedSquatJacks = 19
    case tripleUnder = 20
    case weightedTripleUnder = 21
    case elliptical = 22
    case spinning = 23
    case polePaddleForwardWheelchair = 24
    case polePaddleBackwardWheelchair = 25
    case poleHandcycleForwardWheelchair = 26
    case poleHandcycleBackwardWheelchair = 27
    case poleRainbowWheelchair = 28
    case doublePunchForwardWheelchair = 29
    case doublePunchDownWheelchair = 30
    case doublePunchSidewaysWheelchair = 31
    case doublePunchUpWheelchair = 32
    case sitSkiWheelchair = 33
    case sittingJacksWheelchair = 34
    case punchForwardWheelchair = 35
    case punchDownWheelchair = 36
    case punchSidewaysWheelchair = 37
    case punchUpWheelchair = 38
    case punchBagWheelchair = 39
    case poleDdFfUuWheelchair = 40
    case butterflyArmsWheelchair = 41
    case punch = 42
    case invalid = 0xFFFF
}
