/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

public typealias CourseCapabilities = UInt32

public struct CourseCapabilitiesValues {
    public static let processed: CourseCapabilities = 0x00000001
    public static let valid: CourseCapabilities = 0x00000002
    public static let time: CourseCapabilities = 0x00000004
    public static let distance: CourseCapabilities = 0x00000008
    public static let position: CourseCapabilities = 0x00000010
    public static let heartRate: CourseCapabilities = 0x00000020
    public static let power: CourseCapabilities = 0x00000040
    public static let cadence: CourseCapabilities = 0x00000080
    public static let training: CourseCapabilities = 0x00000100
    public static let navigation: CourseCapabilities = 0x00000200
    public static let bikeway: CourseCapabilities = 0x00000400
    public static let aviation: CourseCapabilities = 0x00001000
    public static let invalid = 0x00000000
}
