/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

public enum ExdDataUnits: UInt8, CaseIterable {
    case noUnits = 0
    case laps = 1
    case milesPerHour = 2
    case kilometersPerHour = 3
    case feetPerHour = 4
    case metersPerHour = 5
    case degreesCelsius = 6
    case degreesFarenheit = 7
    case zone = 8
    case gear = 9
    case rpm = 10
    case bpm = 11
    case degrees = 12
    case millimeters = 13
    case meters = 14
    case kilometers = 15
    case feet = 16
    case yards = 17
    case kilofeet = 18
    case miles = 19
    case time = 20
    case enumTurnType = 21
    case percent = 22
    case watts = 23
    case wattsPerKilogram = 24
    case enumBatteryStatus = 25
    case enumBikeLightBeamAngleMode = 26
    case enumBikeLightBatteryStatus = 27
    case enumBikeLightNetworkConfigType = 28
    case lights = 29
    case seconds = 30
    case minutes = 31
    case hours = 32
    case calories = 33
    case kilojoules = 34
    case milliseconds = 35
    case secondPerMile = 36
    case secondPerKilometer = 37
    case centimeter = 38
    case enumCoursePoint = 39
    case bradians = 40
    case enumSport = 41
    case inchesHg = 42
    case mmHg = 43
    case mbars = 44
    case hectoPascals = 45
    case feetPerMin = 46
    case metersPerMin = 47
    case metersPerSec = 48
    case eightCardinal = 49
    case invalid = 0xFF
}
