/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

public enum ExdDisplayType: UInt8, CaseIterable {
    case numerical = 0
    case simple = 1
    case graph = 2
    case bar = 3
    case circleGraph = 4
    case virtualPartner = 5
    case balance = 6
    case stringList = 7
    case string = 8
    case simpleDynamicIcon = 9
    case gauge = 10
    case invalid = 0xFF
}
