/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

public enum File: UInt8, CaseIterable {
    case device = 1
    case settings = 2
    case sport = 3
    case activity = 4
    case workout = 5
    case course = 6
    case schedules = 7
    case weight = 9
    case totals = 10
    case goals = 11
    case bloodPressure = 14
    case monitoringA = 15
    case activitySummary = 20
    case monitoringDaily = 28
    case monitoringB = 32
    case segment = 34
    case segmentList = 35
    case exdConfiguration = 40
    case mfgRangeMin = 0xF7
    case mfgRangeMax = 0xFE
    case invalid = 0xFF
}
