/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

public enum FlyeExerciseName: UInt16, CaseIterable {
    case cableCrossover = 0
    case declineDumbbellFlye = 1
    case dumbbellFlye = 2
    case inclineDumbbellFlye = 3
    case kettlebellFlye = 4
    case kneelingRearFlye = 5
    case singleArmStandingCableReverseFlye = 6
    case swissBallDumbbellFlye = 7
    case armRotations = 8
    case hugATree = 9
    case faceDownInclineReverseFlye = 10
    case inclineReverseFlye = 11
    case rearDeltFlyWheelchair = 12
    case invalid = 0xFFFF
}
