/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

public typealias LanguageBits4 = UInt8

public struct LanguageBits4Values {
    public static let brazilianPortuguese: LanguageBits4 = 0x01
    public static let indonesian: LanguageBits4 = 0x02
    public static let malaysian: LanguageBits4 = 0x04
    public static let vietnamese: LanguageBits4 = 0x08
    public static let burmese: LanguageBits4 = 0x10
    public static let mongolian: LanguageBits4 = 0x20
    public static let invalid = 0x00
}
