/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

public enum MoveExerciseName: UInt16, CaseIterable {
    case archAndCurl = 0
    case armCirclesWithBallBandAndWeight = 1
    case armStretch = 2
    case backMassage = 3
    case bellyBreathing = 4
    case bridgeWithBall = 5
    case diamondLegCrunch = 6
    case diamondLegLift = 7
    case eightPointShoulderOpener = 8
    case footRolling = 9
    case footwork = 10
    case footworkOnDisc = 11
    case forwardFold = 12
    case frogWithBand = 13
    case halfRollUp = 14
    case hamstringCurl = 15
    case hamstringStretch = 16
    case hipStretch = 17
    case hugATreeWithBallBandAndWeight = 18
    case kneeCircles = 19
    case kneeFoldsOnDisc = 20
    case lateralFlexion = 21
    case legStretchWithBand = 22
    case legStretchWithLegCircles = 23
    case lowerLiftOnDisc = 24
    case lungeSquat = 25
    case lungesWithKneeLift = 26
    case mermaidStretch = 27
    case neutralPelvicPosition = 28
    case pelvicClocksOnDisc = 29
    case pilatesPlieSquatsParallelTurnedOutFlatAndHeelsWithChair = 30
    case piriformisStretch = 31
    case plankKneeCrosses = 32
    case plankKneePulls = 33
    case plankUpDowns = 34
    case prayerMudra = 35
    case psoasLungeStretch = 36
    case ribcageBreathing = 37
    case rollDown = 38
    case rollUpWithWeightAndBand = 39
    case saw = 40
    case scapularStabilization = 41
    case scissorsOnDisc = 42
    case seatedHipStretchup = 43
    case seatedTwist = 44
    case shavingTheHeadWithBallBandAndWeight = 45
    case spinalTwist = 46
    case spinalTwistStretch = 47
    case spineStretchForward = 48
    case squatOpenArmTwistPose = 49
    case squatsWithBall = 50
    case standAndHang = 51
    case standingSideStretch = 52
    case standingSingleLegForwardBendWithItBandOpener = 53
    case straightLegCrunchWithLegLift = 54
    case straightLegCrunchWithLegLiftWithBall = 55
    case straightLegCrunchWithLegsCrossed = 56
    case straightLegCrunchWithLegsCrossedWithBall = 57
    case straightLegDiagonalCrunch = 58
    case straightLegDiagonalCrunchWithBall = 59
    case tailboneCurl = 60
    case throatLock = 61
    case tickTockSideRoll = 62
    case twist = 63
    case vLegCrunches = 64
    case vSit = 65
    case forwardFoldWheelchair = 66
    case forwardFoldPlusWheelchair = 67
    case armCirclesLowForwardWheelchair = 68
    case armCirclesMidForwardWheelchair = 69
    case armCirclesHighForwardWheelchair = 70
    case armCirclesLowBackwardWheelchair = 71
    case armCirclesMidBackwardWheelchair = 72
    case armCirclesHighBackwardWheelchair = 73
    case coreTwistsWheelchair = 74
    case armRaiseWheelchair = 75
    case chestExpandWheelchair = 76
    case armExtendWheelchair = 77
    case forwardBendWheelchair = 78
    case toeTouchWheelchair = 79
    case extendedToeTouchWheelchair = 80
    case seatedArmCircles = 81
    case trunkRotations = 82
    case seatedTrunkRotations = 83
    case toeTouch = 84
    case invalid = 0xFFFF
}
