/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

public enum RowExerciseName: UInt16, CaseIterable {
    case barbellStraightLegDeadliftToRow = 0
    case cableRowStanding = 1
    case dumbbellRow = 2
    case elevatedFeetInvertedRow = 3
    case weightedElevatedFeetInvertedRow = 4
    case facePull = 5
    case facePullWithExternalRotation = 6
    case invertedRowWithFeetOnSwissBall = 7
    case weightedInvertedRowWithFeetOnSwissBall = 8
    case kettlebellRow = 9
    case modifiedInvertedRow = 10
    case weightedModifiedInvertedRow = 11
    case neutralGripAlternatingDumbbellRow = 12
    case oneArmBentOverRow = 13
    case oneLeggedDumbbellRow = 14
    case renegadeRow = 15
    case reverseGripBarbellRow = 16
    case ropeHandleCableRow = 17
    case seatedCableRow = 18
    case seatedDumbbellRow = 19
    case singleArmCableRow = 20
    case singleArmCableRowAndRotation = 21
    case singleArmInvertedRow = 22
    case weightedSingleArmInvertedRow = 23
    case singleArmNeutralGripDumbbellRow = 24
    case singleArmNeutralGripDumbbellRowAndRotation = 25
    case suspendedInvertedRow = 26
    case weightedSuspendedInvertedRow = 27
    case tBarRow = 28
    case towelGripInvertedRow = 29
    case weightedTowelGripInvertedRow = 30
    case underhandGripCableRow = 31
    case vGripCableRow = 32
    case wideGripSeatedCableRow = 33
    case alternatingDumbbellRow = 34
    case invertedRow = 35
    case row = 36
    case weightedRow = 37
    case indoorRow = 38
    case bandedFacePulls = 39
    case chestSupportedDumbbellRow = 40
    case declineRingRow = 41
    case elevatedRingRow = 42
    case rdlBentOverRowWithBarbellDumbbell = 43
    case ringRow = 44
    case barbellRow = 45
    case bentOverRowWithBarbell = 46
    case bentOverRowWithDumbell = 47
    case seatedUnderhandGripCableRow = 48
    case trxInvertedRow = 49
    case weightedInvertedRow = 50
    case weightedTrxInvertedRow = 51
    case dumbbellRowWheelchair = 52
    case invalid = 0xFFFF
}
