/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

public enum SandbagExerciseName: UInt16, CaseIterable {
    case aroundTheWorld = 0
    case backSquat = 1
    case bearCrawlPullThrough = 2
    case bearHugSquat = 3
    case clean = 4
    case cleanAndPress = 5
    case curl = 6
    case frontCarry = 7
    case frontSquat = 8
    case lunge = 9
    case overheadPress = 10
    case plankPullThrough = 11
    case rotationalLunge = 12
    case row = 13
    case russianTwist = 14
    case shouldering = 15
    case shoveling = 16
    case sideLunge = 17
    case sprint = 18
    case zercherSquat = 19
    case invalid = 0xFFFF
}
