/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

public typealias SportBits3 = UInt8

public struct SportBits3Values {
    public static let driving: SportBits3 = 0x01
    public static let golf: SportBits3 = 0x02
    public static let hangGliding: SportBits3 = 0x04
    public static let horsebackRiding: SportBits3 = 0x08
    public static let hunting: SportBits3 = 0x10
    public static let fishing: SportBits3 = 0x20
    public static let inlineSkating: SportBits3 = 0x40
    public static let rockClimbing: SportBits3 = 0x80
    public static let invalid = 0x00
}
