/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

public enum SquatExerciseName: UInt16, CaseIterable {
    case legPress = 0
    case backSquatWithBodyBar = 1
    case backSquats = 2
    case weightedBackSquats = 3
    case balancingSquat = 4
    case weightedBalancingSquat = 5
    case barbellBackSquat = 6
    case barbellBoxSquat = 7
    case barbellFrontSquat = 8
    case barbellHackSquat = 9
    case barbellHangSquatSnatch = 10
    case barbellLateralStepUp = 11
    case barbellQuarterSquat = 12
    case barbellSiffSquat = 13
    case barbellSquatSnatch = 14
    case barbellSquatWithHeelsRaised = 15
    case barbellStepover = 16
    case barbellStepUp = 17
    case benchSquatWithRotationalChop = 18
    case weightedBenchSquatWithRotationalChop = 19
    case bodyWeightWallSquat = 20
    case weightedWallSquat = 21
    case boxStepSquat = 22
    case weightedBoxStepSquat = 23
    case bracedSquat = 24
    case crossedArmBarbellFrontSquat = 25
    case crossoverDumbbellStepUp = 26
    case dumbbellFrontSquat = 27
    case dumbbellSplitSquat = 28
    case dumbbellSquat = 29
    case dumbbellSquatClean = 30
    case dumbbellStepover = 31
    case dumbbellStepUp = 32
    case elevatedSingleLegSquat = 33
    case weightedElevatedSingleLegSquat = 34
    case figureFourSquats = 35
    case weightedFigureFourSquats = 36
    case gobletSquat = 37
    case kettlebellSquat = 38
    case kettlebellSwingOverhead = 39
    case kettlebellSwingWithFlipToSquat = 40
    case lateralDumbbellStepUp = 41
    case oneLeggedSquat = 42
    case overheadDumbbellSquat = 43
    case overheadSquat = 44
    case partialSingleLegSquat = 45
    case weightedPartialSingleLegSquat = 46
    case pistolSquat = 47
    case weightedPistolSquat = 48
    case plieSlides = 49
    case weightedPlieSlides = 50
    case plieSquat = 51
    case weightedPlieSquat = 52
    case prisonerSquat = 53
    case weightedPrisonerSquat = 54
    case singleLegBenchGetUp = 55
    case weightedSingleLegBenchGetUp = 56
    case singleLegBenchSquat = 57
    case weightedSingleLegBenchSquat = 58
    case singleLegSquatOnSwissBall = 59
    case weightedSingleLegSquatOnSwissBall = 60
    case squat = 61
    case weightedSquat = 62
    case squatsWithBand = 63
    case staggeredSquat = 64
    case weightedStaggeredSquat = 65
    case stepUp = 66
    case weightedStepUp = 67
    case suitcaseSquats = 68
    case sumoSquat = 69
    case sumoSquatSlideIn = 70
    case weightedSumoSquatSlideIn = 71
    case sumoSquatToHighPull = 72
    case sumoSquatToStand = 73
    case weightedSumoSquatToStand = 74
    case sumoSquatWithRotation = 75
    case weightedSumoSquatWithRotation = 76
    case swissBallBodyWeightWallSquat = 77
    case weightedSwissBallWallSquat = 78
    case thrusters = 79
    case unevenSquat = 80
    case weightedUnevenSquat = 81
    case waistSlimmingSquat = 82
    case wallBall = 83
    case wideStanceBarbellSquat = 84
    case wideStanceGobletSquat = 85
    case zercherSquat = 86
    case kbsOverhead = 87
    case squatAndSideKick = 88
    case squatJumpsInNOut = 89
    case pilatesPlieSquatsParallelTurnedOutFlatAndHeels = 90
    case releveStraightLegAndKneeBentWithOneLegVariation = 91
    case alternatingBoxDumbbellStepUps = 92
    case dumbbellOverheadSquatSingleArm = 93
    case dumbbellSquatSnatch = 94
    case medicineBallSquat = 95
    case wallBallSquatAndPress = 97
    case squatAmericanSwing = 98
    case airSquat = 100
    case dumbbellThrusters = 101
    case overheadBarbellSquat = 102
    case invalid = 0xFFFF
}
