/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

public enum SuspensionExerciseName: UInt16, CaseIterable {
    case chestFly = 0
    case chestPress = 1
    case crunch = 2
    case curl = 3
    case dip = 4
    case facePull = 5
    case gluteBridge = 6
    case hamstringCurl = 7
    case hipDrop = 8
    case invertedRow = 9
    case kneeDriveJump = 10
    case kneeToChest = 11
    case latPullover = 12
    case lunge = 13
    case mountainClimber = 14
    case pendulum = 15
    case pike = 16
    case plank = 17
    case powerPull = 18
    case pullUp = 19
    case pushUp = 20
    case reverseMountainClimber = 21
    case reversePlank = 22
    case rollout = 23
    case row = 24
    case sideLunge = 25
    case sidePlank = 26
    case singleLegDeadlift = 27
    case singleLegSquat = 28
    case sitUp = 29
    case split = 30
    case squat = 31
    case squatJump = 32
    case tricepPress = 33
    case yFly = 34
    case invalid = 0xFFFF
}
