/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

public enum TotalBodyExerciseName: UInt16, CaseIterable {
    case burpee = 0
    case weightedBurpee = 1
    case burpeeBoxJump = 2
    case weightedBurpeeBoxJump = 3
    case highPullBurpee = 4
    case manMakers = 5
    case oneArmBurpee = 6
    case squatThrusts = 7
    case weightedSquatThrusts = 8
    case squatPlankPushUp = 9
    case weightedSquatPlankPushUp = 10
    case standingTRotationBalance = 11
    case weightedStandingTRotationBalance = 12
    case barbellBurpee = 13
    case burpeeBoxJumpOverYesLiterallyJumpingOverTheBox = 15
    case burpeeBoxJumpStepUpOver = 16
    case lateralBarbellBurpee = 17
    case totalBodyBurpeeOverBar = 18
    case burpeeBoxJumpOver = 19
    case burpeeWheelchair = 20
    case invalid = 0xFFFF
}
