/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

public enum TricepsExtensionExerciseName: UInt16, CaseIterable {
    case benchDip = 0
    case weightedBenchDip = 1
    case bodyWeightDip = 2
    case cableKickback = 3
    case cableLyingTricepsExtension = 4
    case cableOverheadTricepsExtension = 5
    case dumbbellKickback = 6
    case dumbbellLyingTricepsExtension = 7
    case ezBarOverheadTricepsExtension = 8
    case inclineDip = 9
    case weightedInclineDip = 10
    case inclineEzBarLyingTricepsExtension = 11
    case lyingDumbbellPulloverToExtension = 12
    case lyingEzBarTricepsExtension = 13
    case lyingTricepsExtensionToCloseGripBenchPress = 14
    case overheadDumbbellTricepsExtension = 15
    case recliningTricepsPress = 16
    case reverseGripPressdown = 17
    case reverseGripTricepsPressdown = 18
    case ropePressdown = 19
    case seatedBarbellOverheadTricepsExtension = 20
    case seatedDumbbellOverheadTricepsExtension = 21
    case seatedEzBarOverheadTricepsExtension = 22
    case seatedSingleArmOverheadDumbbellExtension = 23
    case singleArmDumbbellOverheadTricepsExtension = 24
    case singleDumbbellSeatedOverheadTricepsExtension = 25
    case singleLegBenchDipAndKick = 26
    case weightedSingleLegBenchDipAndKick = 27
    case singleLegDip = 28
    case weightedSingleLegDip = 29
    case staticLyingTricepsExtension = 30
    case suspendedDip = 31
    case weightedSuspendedDip = 32
    case swissBallDumbbellLyingTricepsExtension = 33
    case swissBallEzBarLyingTricepsExtension = 34
    case swissBallEzBarOverheadTricepsExtension = 35
    case tabletopDip = 36
    case weightedTabletopDip = 37
    case tricepsExtensionOnFloor = 38
    case tricepsPressdown = 39
    case weightedDip = 40
    case alternatingDumbbellLyingTricepsExtension = 41
    case tricepsPress = 42
    case dumbbellKickbackWheelchair = 43
    case overheadDumbbellTricepsExtensionWheelchair = 44
    case invalid = 0xFFFF
}
