/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////

public enum WarmUpExerciseName: UInt16, CaseIterable {
    case quadrupedRocking = 0
    case neckTilts = 1
    case ankleCircles = 2
    case ankleDorsiflexionWithBand = 3
    case ankleInternalRotation = 4
    case armCircles = 5
    case bentOverReachToSky = 6
    case catCamel = 7
    case elbowToFootLunge = 8
    case forwardAndBackwardLegSwings = 9
    case groiners = 10
    case invertedHamstringStretch = 11
    case lateralDuckUnder = 12
    case neckRotations = 13
    case oppositeArmAndLegBalance = 14
    case reachRollAndLift = 15
    case scorpion = 16
    case shoulderCircles = 17
    case sideToSideLegSwings = 18
    case sleeperStretch = 19
    case slideOut = 20
    case swissBallHipCrossover = 21
    case swissBallReachRollAndLift = 22
    case swissBallWindshieldWipers = 23
    case thoracicRotation = 24
    case walkingHighKicks = 25
    case walkingHighKnees = 26
    case walkingKneeHugs = 27
    case walkingLegCradles = 28
    case walkout = 29
    case walkoutFromPushUpPosition = 30
    case bicepsStretch = 31
    case glutesStretch = 32
    case standingHamstringStretch = 33
    case stretch90_90 = 34
    case stretchAbs = 35
    case stretchButterfly = 36
    case stretchCalf = 37
    case stretchCatCow = 38
    case stretchChildsPose = 39
    case stretchCobra = 40
    case stretchForearms = 41
    case stretchForwardGlutes = 42
    case stretchFrontSplit = 43
    case stretchHamstring = 44
    case stretchHipFlexorAndQuad = 45
    case stretchLat = 46
    case stretchLevatorScapulae = 47
    case stretchLungeWithSpinalTwist = 48
    case stretchLungingHipFlexor = 49
    case stretchLyingAbduction = 50
    case stretchLyingItBand = 51
    case stretchLyingKneeToChest = 52
    case stretchLyingPiriformis = 53
    case stretchLyingSpinalTwist = 54
    case stretchNeck = 55
    case stretchObliques = 56
    case stretchOverUnderShoulder = 57
    case stretchPectoral = 58
    case stretchPigeonPose = 59
    case stretchPiriformis = 60
    case stretchQuad = 61
    case stretchScorpion = 62
    case stretchShoulder = 63
    case stretchSide = 64
    case stretchSideLunge = 65
    case stretchSideSplit = 66
    case stretchStandingItBand = 67
    case stretchStraddle = 68
    case stretchTriceps = 69
    case stretchWallChestAndShoulder = 70
    case neckRotationsWheelchair = 71
    case halfKneelingArmRotation = 72
    case threeWayAnkleMobilization = 73
    case ninetyNinetyHipSwitch = 74
    case activeFrog = 75
    case shoulderSweeps = 76
    case ankleLunges = 77
    case backRollFoamRoller = 78
    case bearCrawl = 79
    case latissimusDorsiFoamRoll = 80
    case reverseTHipOpener = 81
    case shoulderRolls = 82
    case chestOpeners = 83
    case tricepsStretch = 84
    case upperBackStretch = 85
    case hipCircles = 86
    case ankleStretch = 87
    case marchingInPlace = 88
    case tricepsStretchWheelchair = 89
    case upperBackStretchWheelchair = 90
    case invalid = 0xFFFF
}
