/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////


open class OhrSettingsMesg : Mesg {
    public static let timestampFieldNum:UInt8 = 253
    public static let enabledFieldNum:UInt8 = 0

	public init() {
        super.init(mesg: OhrSettingsMesg.createOhrSettingsMesg())
    }

    public override init(mesg: Mesg) {
        super.init(mesg: mesg)
    }

    fileprivate override init(name: String, num: UInt16) {
        super.init(name: name, num: num)
    }

	public func getTimestamp() -> DateTime? {
		guard let value = getFieldValue(fieldNum: OhrSettingsMesg.timestampFieldNum, index:0) as? UInt32 else {
            return nil
        }
		return DateTime(timestamp: value)
	}

	public func setTimestamp(_ value: DateTime) throws {
		try setFieldValue(fieldNum: OhrSettingsMesg.timestampFieldNum, value: value.timestamp)
	}

	public func getEnabled() -> Switch? {
		guard let value = getFieldValue(fieldNum: OhrSettingsMesg.enabledFieldNum, index:0) as? UInt8 else {
            return nil
        }
		return Switch(rawValue: value) ?? .invalid
	}

	public func setEnabled(_ value: Switch) throws {
		try setFieldValue(fieldNum: OhrSettingsMesg.enabledFieldNum, value: value.rawValue)
	}

	public class func createOhrSettingsMesg() -> OhrSettingsMesg {
        let mesg = OhrSettingsMesg(name: "OhrSettings", num: Profile.MesgNum.ohrSettings)
		
		mesg.fields[OhrSettingsMesg.timestampFieldNum] = Field(name: "Timestamp", num: OhrSettingsMesg.timestampFieldNum, type: BaseType.UINT32.rawValue, scale: 1, offset: 0, units: "s", accumulated: false)
		mesg.fields[OhrSettingsMesg.enabledFieldNum] = Field(name: "Enabled", num: OhrSettingsMesg.enabledFieldNum, type: BaseType.ENUM.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
        return mesg
    }
}