/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////


open class PowerZoneMesg : Mesg {
    public static let messageIndexFieldNum:UInt8 = 254
    public static let highValueFieldNum:UInt8 = 1
    public static let nameFieldNum:UInt8 = 2

	public init() {
        super.init(mesg: PowerZoneMesg.createPowerZoneMesg())
    }

    public override init(mesg: Mesg) {
        super.init(mesg: mesg)
    }

    fileprivate override init(name: String, num: UInt16) {
        super.init(name: name, num: num)
    }

	public func getMessageIndex() -> MessageIndex? {
		guard let value = getFieldValue(fieldNum: PowerZoneMesg.messageIndexFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setMessageIndex(_ value: MessageIndex) throws {
		try setFieldValue(fieldNum: PowerZoneMesg.messageIndexFieldNum, value: value)
	}

	public func getHighValue() -> UInt16? {
		guard let value = getFieldValue(fieldNum: PowerZoneMesg.highValueFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setHighValue(_ value: UInt16) throws {
		try setFieldValue(fieldNum: PowerZoneMesg.highValueFieldNum, value: value)
	}

	public func getName() -> String? {
		guard let value = getFieldValue(fieldNum: PowerZoneMesg.nameFieldNum, index:0) as? String else {
            return nil
        }
		return value
	}

	public func setName(_ value: String) throws {
		try setFieldValue(fieldNum: PowerZoneMesg.nameFieldNum, value: value)
	}

	public class func createPowerZoneMesg() -> PowerZoneMesg {
        let mesg = PowerZoneMesg(name: "PowerZone", num: Profile.MesgNum.powerZone)
		
		mesg.fields[PowerZoneMesg.messageIndexFieldNum] = Field(name: "MessageIndex", num: PowerZoneMesg.messageIndexFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[PowerZoneMesg.highValueFieldNum] = Field(name: "HighValue", num: PowerZoneMesg.highValueFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "watts", accumulated: false)
		mesg.fields[PowerZoneMesg.nameFieldNum] = Field(name: "Name", num: PowerZoneMesg.nameFieldNum, type: BaseType.STRING.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
        return mesg
    }
}