/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////


open class SoftwareMesg : Mesg {
    public static let messageIndexFieldNum:UInt8 = 254
    public static let versionFieldNum:UInt8 = 3
    public static let partNumberFieldNum:UInt8 = 5

	public init() {
        super.init(mesg: SoftwareMesg.createSoftwareMesg())
    }

    public override init(mesg: Mesg) {
        super.init(mesg: mesg)
    }

    fileprivate override init(name: String, num: UInt16) {
        super.init(name: name, num: num)
    }

	public func getMessageIndex() -> MessageIndex? {
		guard let value = getFieldValue(fieldNum: SoftwareMesg.messageIndexFieldNum, index:0) as? UInt16 else {
            return nil
        }
		return value
	}

	public func setMessageIndex(_ value: MessageIndex) throws {
		try setFieldValue(fieldNum: SoftwareMesg.messageIndexFieldNum, value: value)
	}

	public func getVersion() -> Float64? {
		guard let value = getFieldValue(fieldNum: SoftwareMesg.versionFieldNum, index:0) as? Float64 else {
            return nil
        }
		return value
	}

	public func setVersion(_ value: Float64) throws {
		try setFieldValue(fieldNum: SoftwareMesg.versionFieldNum, value: value)
	}

	public func getPartNumber() -> String? {
		guard let value = getFieldValue(fieldNum: SoftwareMesg.partNumberFieldNum, index:0) as? String else {
            return nil
        }
		return value
	}

	public func setPartNumber(_ value: String) throws {
		try setFieldValue(fieldNum: SoftwareMesg.partNumberFieldNum, value: value)
	}

	public class func createSoftwareMesg() -> SoftwareMesg {
        let mesg = SoftwareMesg(name: "Software", num: Profile.MesgNum.software)
		
		mesg.fields[SoftwareMesg.messageIndexFieldNum] = Field(name: "MessageIndex", num: SoftwareMesg.messageIndexFieldNum, type: BaseType.UINT16.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
		mesg.fields[SoftwareMesg.versionFieldNum] = Field(name: "Version", num: SoftwareMesg.versionFieldNum, type: BaseType.UINT16.rawValue, scale: 100, offset: 0, units: "", accumulated: false)
		mesg.fields[SoftwareMesg.partNumberFieldNum] = Field(name: "PartNumber", num: SoftwareMesg.partNumberFieldNum, type: BaseType.STRING.rawValue, scale: 1, offset: 0, units: "", accumulated: false)
        return mesg
    }
}