/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.171.0Release
// Tag = production/release/21.171.0-0-g57fed75
/////////////////////////////////////////////////////////////////////////////////////////////


import Foundation

public class OutputStream {
    private(set) var data = Data()
    
    public init() {
    }
    
    var isEmpty: Bool {
        return data.isEmpty
    }
    
    var count: Int {
        return data.count
    }
    
    subscript(index: Data.Index) -> UInt8 { 
        get {
            return data[index]
        }
        set {
            data[index] = newValue
        }
    }
    
    public func append(_ other: Data) {
        self.data.append(other)
    }
    
    public func append(contentsOf bytes: [UInt8]) {
        self.data.append(contentsOf: bytes)
    }
    
    public func append(value: any Numeric) {
        self.data.append(contentsOf: value.bytes)
    }
    
    public func replaceSubrange(_ subrange: Range<Data.Index>, with data: Data) {
        self.data.replaceSubrange(subrange, with: data)
    }
}
